name: Run Unit Tests on Pull Request to Develop Branch

# Trigger the workflow when a pull request is detected for 'develop'
on:
  pull_request:
    branches:
      - develop
    types:
      - opened # Trigger when a pull request is opened
      - synchronize # Trigger when a pull request is updated

# Define jobs to run in this workflow
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Change directory to functions project
        run: cd functions

      - name: Install dependencies
        run: |
          pwd
          npm install

      - name: Test functions logic
        run: npm run test
