name: Run Unit Tests on Pull Request to Develop Branch

# Trigger the workflow when a pull request is detected for 'develop'
on:
  pull_request:
    branches:
      - develop
    types:
      - opened # Trigger when a pull request is opened
      - synchronize # Trigger when a pull request is updated

# Define jobs to run in this workflow
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install functions dependencies
        working-directory: functions
        run: npm install

      - name: Install Firebase CLI
        working-directory: functions
        run: npm install -g firebase-tools

      - name: Run Unit Tests
        working-directory: functions
        env:
          EXPO_IS_GITHUB_PIPELINE: true
        run: npm run test:unit

      - name: Run Integration Tests
        working-directory: functions
        env:
          EXPO_IS_GITHUB_PIPELINE: true
        run: npx firebase emulators:exec --project demo-builtmode "npm test:integration"
