name: Run Tests on Pull Request to Develop

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  server_test:
    name: Server tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: functions/package.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          CI: true
        run: npm run test:unit

      - name: Install shared packages dependencies
        run: |
          cd ..
          cd packages/shared
          npm ci

      - name: Build shared packages
        run: |
          cd ..
          cd packages/shared
          npm run build

      - name: Build functions
        run: |
          cd ..
          npm run build

      - name: Run integration tests with emulators
        env:
          CI: true
        run: npx firebase emulators:exec --project demo-builtmode "npm run test:integration"

  client_test:
    name: Client tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run client unit tests
        env:
          CI: true
        run: npm run test:unit
